export const subj = [
  'Français',
  'Anglais',
  'Mathématiques',
  'Physiques-chimie',
  'Programmtion C++',
  'Programmtion C',
  'Programmtion Java',
  'Systèmes répartis',
  'Conception orientée logicielle',
  "Système d'exploitation",
  'Machines learning',
  'Sécurité et cryptographie',
  'Algorithme avancé',
  'Logique',
  'Recherche operationnelle',
  'Economie',
  'Projet',
  "Droits de l'homme",
  'Réseaux',
  'Transmissions de données',
  'Culture entreprise',
  'Systèmes dynamiques',
  'Analyse de données',
]
